package transcript

import (
	"strings"
	"testing"
)

// fixture is a representative slice of a Claude Code transcript: the line shapes
// the renderer must handle, including ones it must drop.
const fixture = `{"type":"system","subtype":"init","message":{}}
{"type":"user","message":{"role":"user","content":"Should we migrate billing to the new ledger?<system-reminder>internal cwd note</system-reminder>"}}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"thinking","thinking":"weighing options"},{"type":"text","text":"Yes — the new ledger removes the nightly reconcile job."},{"type":"tool_use","name":"Bash","input":{"command":"go test ./...","description":"Run the billing tests"}}]}}
{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"ok 1.2s"}]}}
{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: messages below were generated by local commands</local-command-caveat>"}}
{"type":"user","isMeta":true,"message":{"role":"user","content":"Base directory for this skill: /skills/foo — INJECTED SKILL BODY"}}
{"type":"user","message":{"role":"user","content":"<command-name>/whats-next</command-name>\n  <command-args>now</command-args>"}}
{"type":"user","message":{"role":"user","content":"<system-reminder>only boilerplate</system-reminder>"}}
{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Done. Owner is Dana, target Q3."}]}}
{"type":"file-history-snapshot","snapshot":{"big":"ignored"}}
not even json
{"type":"user","message":{"role":"user","content":[{"type":"text","text":"Here is the diagram"},{"type":"tool_result","content":"noise"}]}}
`

func TestRenderConversation(t *testing.T) {
	out, err := Render(strings.NewReader(fixture))
	if err != nil {
		t.Fatal(err)
	}

	// User prompt is kept; the injected system-reminder is stripped out.
	if !strings.Contains(out, "## User\n\nShould we migrate billing to the new ledger?") {
		t.Fatalf("user turn missing/uncleaned:\n%s", out)
	}
	if strings.Contains(out, "system-reminder") || strings.Contains(out, "internal cwd note") {
		t.Fatalf("system reminder not stripped:\n%s", out)
	}

	// Assistant prose is kept; thinking is dropped; the tool call is summarized.
	if !strings.Contains(out, "Yes — the new ledger removes the nightly reconcile job.") {
		t.Fatalf("assistant text missing:\n%s", out)
	}
	if strings.Contains(out, "weighing options") {
		t.Fatalf("thinking block leaked into output:\n%s", out)
	}
	if !strings.Contains(out, "Bash: Run the billing tests") {
		t.Fatalf("tool call not summarized:\n%s", out)
	}

	// Tool results and the local-command caveat are dropped.
	if strings.Contains(out, "ok 1.2s") || strings.Contains(out, "noise") {
		t.Fatalf("tool_result leaked into output:\n%s", out)
	}
	if strings.Contains(out, "Caveat") {
		t.Fatalf("local-command caveat not dropped:\n%s", out)
	}

	// A pure-boilerplate user message (only a reminder) collapses to nothing.
	if strings.Contains(out, "only boilerplate") {
		t.Fatalf("empty user message should be skipped:\n%s", out)
	}

	// isMeta lines (injected skill bodies, hook prompts) are dropped entirely.
	if strings.Contains(out, "INJECTED SKILL BODY") {
		t.Fatalf("isMeta line leaked into output:\n%s", out)
	}

	// A slash command collapses to "/name args", not raw XML.
	if !strings.Contains(out, "## User\n\n/whats-next now") || strings.Contains(out, "<command-name>") {
		t.Fatalf("command invocation not rendered compactly:\n%s", out)
	}

	// A user array with real text alongside a tool_result keeps the text.
	if !strings.Contains(out, "Here is the diagram") {
		t.Fatalf("user text block dropped:\n%s", out)
	}

	// The full second assistant turn survives.
	if !strings.Contains(out, "Owner is Dana, target Q3.") {
		t.Fatalf("second assistant turn missing:\n%s", out)
	}

	// Non-conversation line types and the malformed line never appear.
	if strings.Contains(out, "ignored") || strings.Contains(out, "not even json") {
		t.Fatalf("non-conversation content leaked:\n%s", out)
	}

	// Turns are ordered user → assistant → ... (string index check).
	if strings.Index(out, "migrate billing") > strings.Index(out, "Owner is Dana") {
		t.Fatalf("turns out of order:\n%s", out)
	}
}

func TestRenderEmpty(t *testing.T) {
	out, err := Render(strings.NewReader(""))
	if err != nil || out != "" {
		t.Fatalf("empty transcript should render empty, got %q (err %v)", out, err)
	}
	// A transcript with only non-conversation lines renders empty too.
	out, _ = Render(strings.NewReader(`{"type":"system","message":{}}` + "\n"))
	if out != "" {
		t.Fatalf("non-conversation-only transcript should be empty, got %q", out)
	}
}

// TestRenderLongLine proves an oversized line (a huge tool result, far past
// bufio.Scanner's default 64KB token cap) does not truncate or break parsing of
// the lines around it.
func TestRenderLongLine(t *testing.T) {
	huge := strings.Repeat("x", 200_000)
	doc := `{"type":"user","message":{"role":"user","content":"first"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"` + huge + `"}]}}` + "\n" +
		`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"after the big line"}]}}` + "\n"
	out, err := Render(strings.NewReader(doc))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "first") || !strings.Contains(out, "after the big line") {
		t.Fatalf("oversized line broke parsing:\n%s", out[:min(len(out), 200)])
	}
	if strings.Contains(out, huge) {
		t.Fatal("tool_result body should not be rendered")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
